name: supported-pythons
description: "Retrieve active (not end-of-life) minor versions of Python supported by a Python package"
branding:
  icon: more-vertical
  color: green

inputs:
  package:
    description: package source repository containing `pyproject.toml`
    required: false
    default: ""
  package-ref:
    description: branch or tag of package source
    required: false
    default: ""
  no-eoas:
    description: also omit end-of-active-support versions of Python
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - if: inputs.package != ''
      run: git clone https://github.com/${{ inputs.package }} ${{ inputs.package_ref && format('--revision={0}', inputs.package_ref) || '' }} ./package/
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: 3
    - id: versions
      run: echo versions=$(pipx run ${{ github.action_path }}/supported_pythons.py --package-source=${{ inputs.package && './package/' || '.' }} ${{ inputs.no-eoas == 'true' && '--no-eoas' || '' }}) >> $GITHUB_OUTPUT
      shell: bash
    - id: oldest
      run: echo version=$(python -c "print(${{ steps.versions.outputs.versions }}[0])") >> $GITHUB_OUTPUT
      shell: bash
    - id: latest
      run: echo version=$(python -c "print(${{ steps.versions.outputs.versions }}[-1])") >> $GITHUB_OUTPUT
      shell: bash

outputs:
  versions:
    description: "Python minor versions as a JSON list"
    value: ${{ steps.versions.outputs.versions }}
  oldest:
    description: "oldest supported Python minor version"
    value: ${{ steps.oldest.outputs.version }}
  latest:
    description: "latest supported Python minor version"
    value: ${{ steps.latest.outputs.version }}
