name: supported-pythons
description: "Retrieve active (not end-of-life) minor versions of Python supported by a Python package"
branding:
  icon: more-vertical
  color: green

inputs:
  package:
    description: package source repository containing `pyproject.toml`
    required: false
    default: ""
  package-ref:
    description: branch / tag of package
    required: false
    default: ""
  no-eoas:
    description: also omit end-of-active-support versions of Python
    required: false
    default: "false"
  latest-only:
    description: only return the latest supported minor version of Python
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - if: inputs.package != ''
      run: git clone https://github.com/${{ inputs.package }} ${{ inputs.package_ref && format('--revision={0}', inputs.package_ref) || '' }} ./package/
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: 3
    - id: supported-pythons
      run: echo versions=$(pipx run ${{ github.action_path }}/supported_pythons.py --package-source=${{ inputs.package && './package/' || '.' }} ${{ inputs.no-eoas != 'false' && '--no-eoas' || '' }} ${{ inputs.latest-only != 'false' && '--latest-only' || '' }}) >> $GITHUB_OUTPUT
      shell: bash

outputs:
  versions:
    description: "Python minor versions"
    value: ${{ steps.supported-pythons.outputs.versions }}
