name: supported Python versions

on:
  workflow_call:
    inputs:
      package:
        description: repository containing package source (defaults to that of calling workflow)
        type: string
        required: false
        default: ""
      package-ref:
        description: branch or tag of package source
        type: string
        required: false
        default: ""
      no-eoas:
        description: also prune end-of-active-support versions of Python
        type: boolean
        required: false
        default: false
      latest-only:
        description: only return the latest supported minor version of Python
        type: boolean
        required: false
        default: false
    outputs:
      versions:
        description: "Python minor versions"
        value: ${{ jobs.supported-pythons.outputs.versions }}

permissions: {}

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: supported-pythons
        uses: ./
        with:
          package: ${{ inputs.package }}
          package-ref: ${{ inputs.package-ref }}
          no-eoas: ${{ inputs.no-eoas }}
          latest-only: ${{ inputs.latest-only }}
    outputs:
      versions: ${{ steps.supported-pythons.outputs.versions }}
