name: supported Python versions

on:
  workflow_call:
    inputs:
      package:
        description: package source repository containing `pyproject.toml` (defaults to that of calling workflow)
        type: string
        required: false
        default: ""
      package-ref:
        description: branch or tag of package source
        type: string
        required: false
        default: ""
      no-eoas:
        description: also prune end-of-active-support versions of Python
        type: boolean
        required: false
        default: false
    outputs:
      versions:
        description: "Python minor versions as a JSON list"
        value: ${{ jobs.supported-pythons.outputs.versions }}
      oldest:
        description: "oldest supported Python minor version"
        value: ${{ jobs.supported-pythons.outputs.oldest }}
      latest:
        description: "latest supported Python minor version"
        value: ${{ jobs.supported-pythons.outputs.latest }}

permissions: {}

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: zacharyburnett/supported-pythons
          ref: 1.0.0
      - id: supported-pythons
        uses: ./
        with:
          package: ${{ inputs.package }}
          package-ref: ${{ inputs.package-ref }}
          no-eoas: ${{ inputs.no-eoas }}
    outputs:
      versions: ${{ steps.supported-pythons.outputs.versions }}
      oldest: ${{ steps.supported-pythons.outputs.oldest }}
      latest: ${{ steps.supported-pythons.outputs.latest }}
