name: test

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - spacetelescope/romancal
          - psf/requests
      fail-fast: false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - id: supported-pythons
        uses: ./
        with:
          package: ${{ matrix.repository }}
  test-workflow:
    strategy:
      matrix:
        repository:
          - spacetelescope/romancal
          - psf/requests
      fail-fast: false
    uses: ./.github/workflows/supported-pythons.yml
    with:
      package: ${{ matrix.repository }}
