name: test

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - spacetelescope/romancal
          - psf/requests
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - id: supported-pythons
        uses: ./
        with:
          package: ${{ matrix.repository }}
      - run: echo ${{ steps.supported-pythons.outputs.versions }}
      - run: echo ${{ steps.supported-pythons.outputs.oldest }}
      - run: echo ${{ steps.supported-pythons.outputs.latest }}
  test-workflow:
    strategy:
      matrix:
        repository:
          - spacetelescope/romancal
          - psf/requests
      fail-fast: false
    uses: ./.github/workflows/supported-pythons.yml
    with:
      package: ${{ matrix.repository }}
