name: test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - spacetelescope/romancal
          - psf/requests
      fail-fast: false
    steps:
      - name: checkout action
        uses: actions/checkout@v6
      - name: checkout package source
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.repository }}
          path: ${{ matrix.repository }}
      - id: supported-pythons
        uses: ./
        with:
          package: ${{ matrix.repository }}
      - run: echo ${{ steps.supported-pythons.outputs.versions }}
